name: firebase_database_repository
description: A DatabaseAdapter for the firebase database as used by the database_repository package
version: 1.0.3
repository: https://github.com/glassp/firebase_database_repository

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.8
  database_repository: ^1.1.0
  firebase_core: ^1.12.0
  uuid: ^3.0.6
  
dev_dependencies:
  effective_dart: ^1.3.2